#/bin/bash!

SIZE=$1

if [ "$SIZE" = "" ] 
 then
  echo "Please input your file size as  in order of MBytes! It just accepts integers, ok?!"
  exit 0
fi

# 100000 interactions ~ 200MByte

INTERACTIONS=$((SIZE * 5 * 100000 / 5))
echo "File of $SIZE GBytes aproximated. Generating..."

for i in $(seq 1 $INTERACTIONS); do
 echo "
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== " >> dumbfile.txt
done

echo "20% concluded..."

for i in $(seq 1 $INTERACTIONS); do
 echo "
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== " >> dumbfile.txt
done

echo "40% concluded..."

for i in $(seq 1 $INTERACTIONS); do
 echo "
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== " >> dumbfile.txt
done

echo "60% concluded..."

for i in $(seq 1 $INTERACTIONS); do
 echo "
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== " >> dumbfile.txt
done

echo "80% concluded..."

for i in $(seq 1 $INTERACTIONS); do
 echo "
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA==
TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== TVBMUyBJUyBOT1QgREVBRA== " >> dumbfile.txt
done

echo "100% concluded!"

